Add personal cac and fix migration manifest. Also fix server to run in tandem with milmove app

diff --git a/scripts/update-migrations-manifest b/scripts/update-migrations-manifest
--- a/scripts/update-migrations-manifest
+++ b/scripts/update-migrations-manifest
@@ -11,7 +11,6 @@ readonly DIR
 # If in CI exit immediately, since pre-commit might reorder the manifest on branches not in sync with master.
 [[ "${CI:-}" == "true" ]] && exit 0
 
-for application in app orders; do
-  echo -e "# This is the migrations manifest.\n# If a migration is not recorded here, then it will error." > "$DIR/../migrations/${application}/migrations_manifest.txt"
-  find "${DIR}/../migrations/${application}/schema" "${DIR}/../migrations/${application}/secure"  -type f \( -name "*.up.sql" -o -name "*.up.fizz" \) -exec basename {} \; | sort | uniq | grep -v "^schema[.]sql$" >> "$DIR/../migrations/${application}/migrations_manifest.txt" || true
-done
+application=orders
+echo -e "# This is the migrations manifest.\n# If a migration is not recorded here, then it will error." > "$DIR/../migrations/${application}/migrations_manifest.txt"
+find "${DIR}/../migrations/${application}/schema" "${DIR}/../migrations/${application}/secure"  -type f \( -name "*.up.sql" -o -name "*.up.fizz" \) -exec basename {} \; | sort | uniq | grep -v "^schema[.]sql$" >> "$DIR/../migrations/${application}/migrations_manifest.txt" || true
